###~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~###
###                example configuration file                ###
###~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~###

#logger:
#  level: "debug"
#  output_path: "jackal.log"

host:
  domain: jackal.im
  tls:
    cert_file: ""
    privkey_file: ""

service:
  listener:
    port: 5222
    req_timeout: 60s
    transport: socket
    sasl:
      mechanisms:
      - scram_sha_1
      - scram_sha_256
      - scram_sha_512
      - scram_sha3_512

      # Authentication gateway
      # (proto: https://github.com/jackal-xmpp/jackal-proto/blob/master/jackal/proto/authenticator/v1/authenticator.proto)
      external:
        address: 127.0.0.1:4567
        is_secure: false

modules:
#  enabled:
#    - roster
#    - offline
#    - last        # XEP-0012: Last Activity
#    - disco       # XEP-0030: Service Discovery
#    - private     # XEP-0049: Private XML Storage
#    - vcard       # XEP-0054: vcard-temp
#    - version     # XEP-0092: Software Version
#    - caps        # XEP-0115: Entity Capabilities
#    - blocklist   # XEP-0191: Blocking Command
#    - stream_mgmt # XEP-0198: Stream Management
#    - ping        # XEP-0199: XMPP Ping
#    - time        # XEP-0202: Entity Time
#    - carbons     # XEP-0280: Message Carbons
#    - mam         # XEP-0313: Message Archive Management
#
#  version:
#    show_os: true
#
#  offline:
#    queue_size: 300
#
#  ping:
#    ack_timeout: 90s
#    interval: 3m
#    send_pings: true
#    timeout_action: kill
#
#  mam:
#    queue_size: 1500
#
